Repository sofastack/sofa-serverless, pull requests merged in 2023-09, with the labels that each got.

#66 【arklet】add license auto generator and auto formatter and checker
  .github/workflows/arklet_unit_test.yml
  .github/workflows/codecov.yml
  .gitignore
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  arklet/Formatter.xml
  arklet/HEADER
  arklet/arklet-core/pom.xml
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/ArkletComponent.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/ArkletComponentRegistry.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/api/ApiClient.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/api/model/Response.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/api/model/ResponseCode.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/api/tunnel/Tunnel.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/api/tunnel/http/HttpTunnel.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/api/tunnel/http/netty/NettyHttpServer.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/api/tunnel/http/netty/RequestValidation.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/CommandService.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/CommandServiceImpl.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/builtin/BuiltinCommand.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/builtin/handler/HelpHandler.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/builtin/handler/InstallBizHandler.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/builtin/handler/QueryAllBizHandler.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/builtin/handler/SwitchBizHandler.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/builtin/handler/UninstallBizHandler.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/builtin/model/BizModel.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/builtin/model/CommandModel.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/coordinate/BizCommandCoordinator.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/coordinate/CommandMutexException.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/coordinate/CoordinatorConfig.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/coordinate/ExecutionLock.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/meta/AbstractCommandHandler.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/meta/Command.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/meta/CommandType.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/meta/InputMeta.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/meta/Output.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/common/exception/ArkletException.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/common/exception/ArkletInitException.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/common/exception/ArkletRuntimeException.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/common/exception/CommandValidationException.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/common/log/ArkletLoggerFactory.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/ops/UnifiedOperationService.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/ops/UnifiedOperationServiceImpl.java
  arklet/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/CommandTest.java
  arklet/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/CustomCommand.java
  arklet/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/CustomCommandHandler.java
  arklet/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/Input.java
  arklet/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/component/ComponentRegistryTest.java
  arklet/arklet-springboot-starter/pom.xml
  arklet/arklet-springboot-starter/src/main/java/com/alipay/sofa/serverless/arklet/springboot/starter/ArkletAutoConfiguration.java
  arklet/arklet-springboot-starter/src/main/java/com/alipay/sofa/serverless/arklet/springboot/starter/command/MasterBizCmdHandlerCollector.java
  arklet/arklet-springboot-starter/src/main/java/com/alipay/sofa/serverless/arklet/springboot/starter/environment/ConditionalOnMasterBiz.java
  arklet/arklet-springboot-starter/src/main/java/com/alipay/sofa/serverless/arklet/springboot/starter/environment/OnMasterBiz.java
  arklet/arklet-springboot-starter/src/main/java/com/alipay/sofa/serverless/arklet/springboot/starter/listener/ArkletApplicationListener.java
  arklet/check_format.sh
  arklet/pom.xml
  codecov.yml
  pom.xml
Labels: size/XXL, cla:yes

#70 Module controller 0.3
  .github/workflows/module_controller_unit_test.yml
  module-controller/api/v1alpha1/moduledeployment_types.go
  module-controller/api/v1alpha1/well_known_labels.go
  module-controller/cmd/main.go
  module-controller/config/crd/bases/serverless.alipay.com_moduledeployments.yaml
  module-controller/config/rbac/role.yaml
  module-controller/config/samples/dynamic-stock-deployment.yaml
  module-controller/config/samples/module-deployment_v1alpha1_moduledeployment.yaml
  module-controller/go.mod
  module-controller/go.sum
  module-controller/integration-tests/main.go
  module-controller/integration-tests/test_deploy.go
  module-controller/integration-tests/test_deploy_with_beta_and_group.go
  module-controller/internal/arklet/arklet_client.go
  module-controller/internal/constants/finalizer/well_known_finalizers.go
  module-controller/internal/constants/label/well_known_labels.go
  module-controller/internal/controller/module_controller.go
  module-controller/internal/controller/module_controller_suit_test.go
  module-controller/internal/controller/moduledeployment_controller.go
  module-controller/internal/controller/moduledeployment_controller_suit_test.go
  module-controller/internal/controller/moduledeployment_controller_test.go
  module-controller/internal/controller/modulereplicaset_controller.go
  module-controller/internal/controller/modulereplicaset_controller_suit_test.go
  module-controller/internal/controller/suite_test.go
  module-controller/internal/utils/controller_utils.go
Labels: size/XXL, cla:yes

#75 module controller 0.3 bugfix and unit test fix
  module-controller/Dockerfile
  module-controller/config/crd/bases/serverless.alipay.com_moduledeployments.yaml
  module-controller/config/samples/module-deployment_v1alpha1_moduledeployment.yaml
  module-controller/internal/controller/module_controller.go
  module-controller/internal/controller/moduledeployment_controller_suit_test.go
Labels: bug, cla:yes, size/S

#55 添加moduledeployments基础属性校验，添加controller_utils单测
  module-controller/api/v1alpha1/module_types.go
  module-controller/api/v1alpha1/moduledeployment_types.go
  module-controller/config/crd/bases/serverless.alipay.com_moduledeployments.yaml
  module-controller/config/crd/bases/serverless.alipay.com_modulereplicasets.yaml
  module-controller/config/crd/bases/serverless.alipay.com_modules.yaml
  module-controller/config/crd/bases/serverless.alipay.com_moduletemplates.yaml
  module-controller/internal/controller/moduledeployment_controller_suit_test.go
  module-controller/internal/utils/controller_utils_test.go
Labels: First-time contributor, cla:yes, size/L

#78 sofa-serverless-starter
  sofa-serverless-runtime-starter/HEADER
  sofa-serverless-runtime-starter/pom.xml
Labels: cla:yes, size/L

#81 quickstart & status add field
  module-controller/Makefile
  module-controller/api/v1alpha1/module_types.go
  module-controller/api/v1alpha1/zz_generated.deepcopy.go
  module-controller/cmd/main.go
  module-controller/config/crd/bases/serverless.alipay.com_modules.yaml
  module-controller/config/dev/dev.txt
  module-controller/config/samples/dynamic-stock-service.yaml
  module-controller/config/samples/module-deployment_v1alpha1_moduledeployment.yaml
  module-controller/internal/controller/module_controller.go
  module-controller/internal/controller/modulereplicaset_controller.go
Labels: cla:yes, size/M

#45 Feature: support module scheduling strategy :scatter, stacking
  module-controller/api/v1alpha1/module_types.go
  module-controller/api/v1alpha1/moduledeployment_types.go
  module-controller/api/v1alpha1/zz_generated.deepcopy.go
  module-controller/config/crd/bases/serverless.alipay.com_moduledeployments.yaml
  module-controller/config/crd/bases/serverless.alipay.com_modulereplicasets.yaml
  module-controller/config/crd/bases/serverless.alipay.com_modules.yaml
  module-controller/config/crd/bases/serverless.alipay.com_moduletemplates.yaml
  module-controller/config/rbac/role.yaml
  module-controller/go.mod
  module-controller/go.sum
  module-controller/internal/constants/label/well_known_labels.go
  module-controller/internal/controller/module_controller.go
  module-controller/internal/controller/moduledeployment_controller.go
  module-controller/internal/controller/modulereplicaset_controller.go
  module-controller/internal/controller/modulereplicaset_controller_suit_test.go
  module-controller/internal/controller/modulereplicaset_controller_test.go
  module-controller/internal/controller/suite_test.go
  module-controller/internal/utils/controller_utils.go
  module-controller/internal/utils/controller_utils_test.go
Labels: cla:yes, size/XL

#92 role bug fix
  module-controller/config/rbac/role.yaml
  module-controller/internal/controller/module_controller.go
  module-controller/internal/controller/moduledeployment_controller.go
  module-controller/internal/controller/modulereplicaset_controller.go
Labels: bug, cla:yes, size/S

#95 add pages for sofaserverless
  docs/content/zh-cn/docs/Getting started/_index.md
  docs/content/zh-cn/docs/Overview/_index.md
  docs/content/zh-cn/docs/Overview/app-evolution.png
  docs/content/zh-cn/docs/Overview/cooperation.png
  docs/content/zh-cn/docs/Overview/mid-platform.png
  docs/content/zh-cn/docs/Overview/resource_cost.png
  docs/content/zh-cn/docs/Overview/sdk.png
  docs/content/zh-cn/docs/Tutorials/Base/_index.md
  docs/content/zh-cn/docs/Tutorials/Base/springboot_sofaboot.md
  docs/content/zh-cn/docs/Tutorials/Module/_index.md
  docs/content/zh-cn/docs/Tutorials/Module/attentions.md
  docs/content/zh-cn/docs/Tutorials/Module/class_delegate/_index.md
  docs/content/zh-cn/docs/Tutorials/Module/class_delegate/how_to_open.png
  docs/content/zh-cn/docs/Tutorials/Module/class_delegate/jvm.png
  docs/content/zh-cn/docs/Tutorials/Module/coding/_index.md
  docs/content/zh-cn/docs/Tutorials/Module/coding/spring_context.png
  docs/content/zh-cn/docs/Tutorials/Module/communication.md
  docs/content/zh-cn/docs/Tutorials/Module/customized_support_list.md
  docs/content/zh-cn/docs/Tutorials/Module/datasource/_index.md
  docs/content/zh-cn/docs/Tutorials/Module/datasource/module_name.png
  docs/content/zh-cn/docs/Tutorials/Module/interceptor.md
  docs/content/zh-cn/docs/Tutorials/Module/slimming/_index.md
  docs/content/zh-cn/docs/Tutorials/Module/slimming/exclusion.png
  docs/content/zh-cn/docs/Tutorials/Module/slimming/manual_slim.png
  docs/content/zh-cn/docs/Tutorials/Module/slimming/maven_help.png
  docs/content/zh-cn/docs/Tutorials/Module/slimming/spring_context.png
  docs/content/zh-cn/docs/Tutorials/Module/split.md
  docs/content/zh-cn/docs/Tutorials/Module/static_deploy.md
  docs/content/zh-cn/docs/Tutorials/Module/support_list.md
  docs/content/zh-cn/docs/Tutorials/Module/test.md
  docs/content/zh-cn/docs/Tutorials/ModuleOps/_index.md
  docs/content/zh-cn/docs/Tutorials/ModuleOps/arklet.md
  docs/content/zh-cn/docs/Tutorials/ModuleOps/deploy_rollback.md
  docs/content/zh-cn/docs/Tutorials/ModuleOps/deploy_strategy.md
  docs/content/zh-cn/docs/Tutorials/ModuleOps/incompatible.md
  docs/content/zh-cn/docs/Tutorials/ModuleOps/on_off.md
  docs/content/zh-cn/docs/Tutorials/ModuleOps/scale_replace.md
  docs/content/zh-cn/docs/Tutorials/ModuleOps/traffic.md
  docs/content/zh-cn/docs/Tutorials/_index.md
  docs/content/zh-cn/docs/Tutorials/multi-bear.md
  docs/content/zh-cn/docs/Tutorials/tutorial2.md
Labels: size/XXL, cla:yes

#97 remove example docs
  docs/content/zh-cn/docs/Tasks/Ponycopters/_index.md
  docs/content/zh-cn/docs/Tasks/Ponycopters/configuring-ponycopters.md
  docs/content/zh-cn/docs/Tasks/Ponycopters/launching-ponycopters.md
  docs/content/zh-cn/docs/Tasks/_index.md
  docs/content/zh-cn/docs/Tasks/beds.md
  docs/content/zh-cn/docs/Tasks/porridge.md
  docs/content/zh-cn/docs/Tasks/task.md
  docs/content/zh-cn/user-cases/_index.md
  docs/hugo.toml
Labels: size/XXL, cla:yes

#98 move netlify config to sub dir
  docs/netlify.toml
Labels: cla:yes, size/XS

#99 optimize code
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/builtin/model/PluginInfo.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/health/HealthService.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/health/HealthServiceImpl.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/health/indicator/CpuIndicator.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/health/indicator/Indicator.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/health/indicator/JvmIndicator.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/util/ConvertUtils.java
  arklet/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/HealthHandlerTest.java
  arklet/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/health/HealthTests.java
  arklet/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/health/custom/CustomIndicator.java
  arklet/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/health/indicator/IndicatorTests.java
  arklet/arklet-springboot-starter/src/main/java/com/alipay/sofa/serverless/arklet/springboot/starter/health/extension/indicator/MasterBizHealthIndicator.java
Labels: cla:yes, size/L

#106 update arklet to 0.3.0-SNAPSHOT
  .github/workflows/arklet_release.yml
  .github/workflows/arklet_unit_test.yml
  .github/workflows/codecov.yml
  .github/workflows/stale.yml
  arklet/pom.xml
Labels: cla:yes, size/L

#107 Update arklet_release.yml
  .github/workflows/arklet_release.yml
Labels: cla:yes, size/XS

#110 release arklet and base runtime by github action workflow
  arklet/arklet-springboot-starter/src/main/java/com/alipay/sofa/serverless/arklet/springboot/starter/health/HealthAutoConfiguration.java
  arklet/pom.xml
  sofa-serverless-runtime-starter/pom.xml
Labels: cla:yes, size/M

#112 replicas = -1 表示对等架构
  module-controller/api/v1alpha1/moduledeployment_types.go
  module-controller/config/crd/bases/serverless.alipay.com_moduledeployments.yaml
  module-controller/config/samples/module-deployment_v1alpha1_moduledeployment.yaml
  module-controller/internal/controller/moduledeployment_controller_suit_test.go
Labels: cla:yes, size/S

#22 Feature: support batch deployment strategy
  module-controller/api/v1alpha1/moduledeployment_types.go
  module-controller/config/crd/bases/serverless.alipay.com_moduledeployments.yaml
  module-controller/config/samples/dynamic-stock-deployment.yaml
  module-controller/config/samples/module-deployment_v1alpha1_moduledeployment.yaml
  module-controller/internal/arklet/arklet_client.go
  module-controller/internal/constants/label/well_known_labels.go
  module-controller/internal/controller/module_controller.go
  module-controller/internal/controller/moduledeployment_controller.go
  module-controller/internal/controller/moduledeployment_controller_suit_test.go
  module-controller/internal/controller/moduledeployment_controller_test.go
  module-controller/internal/controller/modulereplicaset_controller.go
  module-controller/internal/controller/modulereplicaset_controller_suit_test.go
  module-controller/internal/controller/modulereplicaset_controller_test.go
  module-controller/internal/controller/suite_test.go
Labels: cla:yes, size/XL

#118 Feat.module url
  module-controller/internal/controller/module_controller.go
  module-controller/internal/controller/module_controller_suit_test.go
  module-controller/internal/controller/moduledeployment_controller.go
  module-controller/internal/controller/modulereplicaset_controller.go
Labels: cla:yes, size/S

#85 Increase the usage of MetaSpace in computing
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/CommandServiceImpl.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/meta/Output.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/record/MetaSpaceRecord.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/record/ProcessRecord.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/record/ProcessRecordHolder.java
  arklet/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/health/HealthServiceImpl.java
  arklet/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/CommandTests.java
  arklet/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/HealthHandlerTest.java
Labels: cla:yes, size/L

#91 Module controller 0.4 scaleup then scaledown
  .github/workflows/module_controller_ci_build_deploy_to_aliyun.yml
  module-controller/PROJECT
  module-controller/api/v1alpha1/module_types.go
  module-controller/api/v1alpha1/moduledeployment_types.go
  module-controller/api/v1alpha1/modulereplicaset_types.go
  module-controller/api/v1alpha1/zz_generated.deepcopy.go
  module-controller/cmd/main.go
  module-controller/config/crd/bases/serverless.alipay.com_moduledeployments.yaml
  module-controller/config/crd/bases/serverless.alipay.com_modulereplicasets.yaml
  module-controller/config/crd/bases/serverless.alipay.com_modules.yaml
  module-controller/config/crd/bases/serverless.alipay.com_moduletemplates.yaml
  module-controller/config/rbac/role.yaml
  module-controller/config/samples/dynamic-stock-deployment.yaml
  module-controller/config/samples/kustomization.yaml
  module-controller/config/samples/module-deployment-controller.yaml
  module-controller/config/samples/module-deployment_v1alpha1_moduledeployment_facade.yaml
  module-controller/config/samples/module-deployment_v1alpha1_moduledeployment_provider.yaml
  module-controller/go.mod
  module-controller/go.sum
  module-controller/internal/arklet/arklet_client.go
  module-controller/internal/constants/finalizer/well_known_finalizers.go
  module-controller/internal/constants/label/well_known_labels.go
  module-controller/internal/controller/module_controller.go
  module-controller/internal/controller/module_controller_suit_test.go
  module-controller/internal/controller/moduledeployment_controller.go
  module-controller/internal/controller/moduledeployment_controller_suit_test.go
  module-controller/internal/controller/modulereplicaset_controller.go
  module-controller/internal/controller/modulereplicaset_controller_suit_test.go
  module-controller/internal/controller/modulereplicaset_controller_test.go
  module-controller/internal/controller/pod_controller.go
  module-controller/internal/controller/pod_controller_suit_test.go
  module-controller/internal/controller/suite_test.go
  module-controller/internal/utils/controller_utils.go
  module-controller/internal/utils/controller_utils_test.go
Labels: size/XXL, cla:yes

#130 基于v0.4版本强推基线变更
  module-controller/internal/controller/moduledeployment_controller.go
  module-controller/internal/controller/moduledeployment_controller_suit_test.go
  module-controller/internal/controller/moduledeployment_controller_test.go
Labels: cla:yes, size/M

#131 Feature: support batch confirm & GrayTime & useBeta
  module-controller/api/v1alpha1/moduledeployment_types.go
  module-controller/api/v1alpha1/zz_generated.deepcopy.go
  module-controller/cmd/main.go
  module-controller/config/crd/bases/serverless.alipay.com_moduledeployments.yaml
  module-controller/config/samples/module-deployment_v1alpha1_moduledeployment_provider.yaml
  module-controller/internal/controller/module_controller_suit_test.go
  module-controller/internal/controller/moduledeployment_controller.go
  module-controller/internal/controller/moduledeployment_controller_suit_test.go
  module-controller/internal/controller/modulereplicaset_controller.go
  module-controller/internal/controller/pod_controller.go
Labels: cla:yes, size/L

#133 add ut
  sofa-serverless-runtime/arklet-core/pom.xml
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/builtin/model/PluginInfo.java
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/health/HealthService.java
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/health/HealthServiceImpl.java
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/health/indicator/CpuIndicator.java
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/health/indicator/Indicator.java
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/health/indicator/JvmIndicator.java
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/util/ConvertUtils.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/BaseTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/handler/BaseHandlerTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/handler/HealthHandlerTests.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/handler/HelpHandlerTests.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/handler/InstallBizHandlerTests.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/handler/UninstallBizHandlerTests.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/component/ComponentRegistryTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/health/HealthServiceTests.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/health/HealthTests.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/health/custom/CustomBizManagerService.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/health/custom/CustomIndicator.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/health/custom/CustomPluginManagerService.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/health/custom/model/CustomBiz.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/health/custom/model/CustomPlugin.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/health/indicator/IndicatorTests.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/util/AssertUtilsTests.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/util/ConvertUtilsTests.java
  sofa-serverless-runtime/arklet-springboot-starter/pom.xml
  sofa-serverless-runtime/arklet-springboot-starter/src/main/java/com/alipay/sofa/serverless/arklet/springboot/starter/health/extension/indicator/MasterBizHealthIndicator.java
  sofa-serverless-runtime/pom.xml
Labels: size/XXL, cla:yes

#134 update version to 0.5.0
  .github/workflows/arklet_unit_test.yml
  docs/content/zh-cn/docs/tutorials/base-create/springboot-and-sofaboot.md
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/M
