Repository sofastack/sofa-serverless, pull requests merged in 2023-12, with the labels that each got.

#356 先扩后缩ci test
  .github/workflows/module_controller_ci_build_batch_deploy_to_aliyun.yml
  .github/workflows/module_controller_ci_build_batch_scaleup_then_scaledown_deploy_to_aliyun.yml
  .github/workflows/module_controller_ci_build_deploy_to_aliyun.yml
  module-controller/config/samples/ci/module-deployment_v1alpha1_moduledeployment_batch_scaleup_then_scaledown_provider.yaml
Labels: cla:yes, size/L

#360 Update module-dev-arkctl.md
  docs/content/zh-cn/docs/tutorials/module-development/module-dev-arkctl.md
Labels: cla:yes, size/XS

#361 update apollo config
  samples/springboot-samples/config/apollo/config/docker-compose.yml
  samples/springboot-samples/config/apollo/config/sql/apolloconfigdb.sql
  samples/springboot-samples/config/apollo/config/sql/apolloportaldb.sql
Labels: cla:yes, size/L

#368 update sofa ark version
  docs/content/zh-cn/docs/tutorials/base-create/springboot-and-sofaboot.md
  docs/content/zh-cn/docs/tutorials/module-development/module-slimming.md
  docs/public/docs/_print/index.html
  docs/public/docs/tutorials/_print/index.html
  docs/public/docs/tutorials/base-create/_print/index.html
  docs/public/docs/tutorials/base-create/springboot-and-sofaboot/index.html
  docs/public/docs/tutorials/module-development/_print/index.html
  docs/public/docs/tutorials/module-development/module-slimming/index.html
  samples/dubbo-samples/rpc/dubbo26/pom.xml
  samples/dubbo-samples/rpc/dubbo27/pom.xml
  samples/dubbo-samples/rpc/dubbo3/pom.xml
  samples/sofaboot-samples/dynamic-stock/README.md
  samples/sofaboot-samples/pom.xml
  samples/springboot-samples/pom.xml
  samples/springboot-samples/web/webflux/biz/pom.xml
  samples/springboot3-samples/db/mybatis/README.md
  samples/springboot3-samples/logging/README.md
  samples/springboot3-samples/msg/kafka/README.md
  samples/springboot3-samples/web/tomcat/README.md
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/health/custom/model/CustomPlugin.java
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/M

#371 先扩后缩ci test增加扩容，缩容，删除模块，删除pod校验
  .github/workflows/module_controller_ci_build_batch_scaleup_then_scaledown_deploy_to_aliyun.yml
  module-controller/config/samples/ci/module-deployment_v1alpha1_moduledeployment_batch_scaledown_scaleup_then_scaledown_provider.yaml
Labels: cla:yes, size/XL

#307 feat(ark-serverless): support apollo
  samples/springboot-samples/config/apollo/base/pom.xml
  sofa-serverless-runtime/sofa-serverless-adapter-ext/pom.xml
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-apollo/README.md
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-apollo/pom.xml
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-apollo/src/main/java/com/alipay/sofa/serverless/adapter/ApolloAdapterActivator.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-apollo/src/main/java/com/ctrip/framework/apollo/spring/boot/ApolloApplicationContextInitializer.java
Labels: cla:yes, size/XL

#373 fix pom modules
  samples/springboot-samples/pom.xml
Labels: bug, cla:yes, size/XS

#375 update version
  samples/sofaboot-samples/pom.xml
Labels: cla:yes, size/XS

#376 add release for snapshot
  .github/workflows/serverless_runtime_snapshot.yml
Labels: cla:yes, size/M

#377 add snapshot for sofaboot samples
  samples/sofaboot-samples/pom.xml
Labels: cla:yes, size/S

#381 enable run with jar for dubbo
  samples/dubbo-samples/rpc/dubbo26/dubbo26base/pom.xml
  samples/dubbo-samples/rpc/dubbo3/dubbo3base/pom.xml
Labels: cla:yes, size/XS

#380 fix sample test: update test app with build jar name base-**
  .github/workflows/ccbin/start.sh
  .github/workflows/serverless_runtime_release.yml
  .github/workflows/serverless_runtime_snapshot.yml
  samples/springboot-samples/web/webflux/base/pom.xml
Labels: bug, cla:yes, size/S

#383 add init mysql for mybatis sample
  samples/springboot-samples/config/apollo/README.md
  samples/springboot-samples/config/apollo/imgs/app-data-name.png
  samples/springboot-samples/config/apollo/imgs/apps.png
  samples/springboot-samples/db/mybatis/README.md
  samples/springboot-samples/db/mybatis/base/src/main/resources/application.properties
  samples/springboot-samples/db/mybatis/biz1/src/main/resources/application.properties
  samples/springboot-samples/db/mybatis/config/init_mysql.sh
Labels: cla:yes, size/M

#384 rm apollo biz override class
  samples/springboot-samples/config/apollo/base/src/main/java/com/ctrip/framework/apollo/spring/boot/ApolloApplicationContextInitializer.java
Labels: cla:yes, size/L

#389 add intro for arklet
  docs/content/zh-cn/docs/contribution-guidelines/arklet/architecture.md
Labels: cla:yes, size/L

#390 remove common-langs
  sofa-serverless-runtime/arklet-core/pom.xml
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/record/ProcessRecordHolder.java
  sofa-serverless-runtime/pom.xml
  sofa-serverless-runtime/sofa-serverless-base-plugin/src/main/java/com/alipay/sofa/serverless/plugin/manager/listener/StaticBatchInstallEventListener.java
Labels: cla:yes, size/S

#170 fix installBiz need bizName and bizVersion
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/builtin/handler/InstallBizHandler.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/handler/InstallBizHandlerTest.java
Labels: bug, cla:yes, size/L

#370 Module reuse base data source
  docs/content/zh-cn/docs/tutorials/module-development/reuse-base-datasource.md
  docs/content/zh-cn/docs/tutorials/module-development/runtime-service-route.md
  samples/springboot-samples/db/mybatis/README.md
  samples/springboot-samples/db/mybatis/biz1/pom.xml
  samples/springboot-samples/db/mybatis/biz1/src/main/java/com/alipay/sofa/biz1/Biz1Application.java
  samples/springboot-samples/db/mybatis/biz1/src/main/java/com/alipay/sofa/biz1/MybatisConfig.java
  samples/springboot-samples/db/mybatis/biz1/src/main/resources/application.properties
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-log4j2/src/main/java/com/alipay/sofa/serverless/log4j2/SOFAServerlessLog4j2SpringContextListener.java
  sofa-serverless-runtime/sofa-serverless-common/src/main/java/com/alipay/sofa/serverless/common/api/SpringBeanFinder.java
  sofa-serverless-runtime/sofa-serverless-common/src/main/java/com/alipay/sofa/serverless/common/service/ServiceProxyFactory.java
  sofa-serverless-runtime/sofa-serverless-common/src/test/java/com/alipay/sofa/serverless/common/SpringServiceAndBeanFinderTest.java
Labels: cla:yes, size/L

#305 add sofa-serverless-adapter-logback
  samples/springboot-samples/logging/logback/base/Dockerfile
  samples/springboot-samples/logging/logback/base/pom.xml
  samples/springboot-samples/logging/logback/base/src/main/java/com/alipay/sofa/web/base/BaseApplication.java
  samples/springboot-samples/logging/logback/base/src/main/java/com/alipay/sofa/web/base/facade/SampleService.java
  samples/springboot-samples/logging/logback/base/src/main/java/com/alipay/sofa/web/base/impl/SampleServiceImpl.java
  samples/springboot-samples/logging/logback/base/src/main/java/com/alipay/sofa/web/base/rest/SampleController.java
  samples/springboot-samples/logging/logback/base/src/main/resources/META-INF/spring/service.xml
  samples/springboot-samples/logging/logback/base/src/main/resources/application.properties
  samples/springboot-samples/logging/logback/base/src/main/resources/logback-spring.xml
  samples/springboot-samples/logging/logback/base/src/test/java/com/alipay/sofa/web/base/BaseApplicationTests.java
  samples/springboot-samples/logging/logback/biz1/pom.xml
  samples/springboot-samples/logging/logback/biz1/src/main/java/com/alipay/sofa/web/biz1/Biz1Application.java
  samples/springboot-samples/logging/logback/biz1/src/main/java/com/alipay/sofa/web/biz1/rest/SampleController.java
  samples/springboot-samples/logging/logback/biz1/src/main/resources/application.properties
  samples/springboot-samples/logging/logback/biz1/src/main/resources/logback-spring.xml
  samples/springboot-samples/logging/logback/biz1/src/test/java/com/alipay/sofa/web/biz1/Biz1ApplicationTests.java
  samples/springboot-samples/logging/logback/biz2/pom.xml
  samples/springboot-samples/logging/logback/biz2/src/main/java/com/alipay/sofa/web/biz2/Biz2Application.java
  samples/springboot-samples/logging/logback/biz2/src/main/java/com/alipay/sofa/web/biz2/rest/SampleController.java
  samples/springboot-samples/logging/logback/biz2/src/main/resources/application.properties
  samples/springboot-samples/logging/logback/biz2/src/main/resources/logback-spring.xml
  samples/springboot-samples/logging/logback/biz2/src/test/java/com/alipay/sofa/web/biz2/Biz2ApplicationTests.java
  samples/springboot-samples/pom.xml
  sofa-serverless-runtime/sofa-serverless-adapter-ext/pom.xml
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/pom.xml
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/main/java/com/alipay/sofa/serverless/logback/SOFAServerlessLogbackLogContextSelector.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/main/java/com/alipay/sofa/serverless/logback/SOFAServerlessLogbackSpringContextListener.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/main/resources/META-INF/spring.factories
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/java/com/alipay/sofa/serverless/logback/LogbackDefaultConfigTest.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/java/com/alipay/sofa/serverless/logback/LogbackTest.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/java/com/alipay/sofa/serverless/logback/bootstrap/SOFABootApplication.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/java/com/alipay/sofa/serverless/logback/helper/Log1Print.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/java/com/alipay/sofa/serverless/logback/helper/Log2Print.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/java/com/alipay/sofa/serverless/logback/helper/LogHelper.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/resources/application-logback.properties
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/resources/application.properties
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/resources/logback-mytest-spring.xml
Labels: First-time contributor, size/XXL, cla:no

#393 添加 nacos sample
  samples/README.md
  samples/springboot-samples/config/nacos/README.md
  samples/springboot-samples/config/nacos/base/pom.xml
  samples/springboot-samples/config/nacos/base/src/main/java/com/alipay/sofa/config/nacos/ConfigController.java
  samples/springboot-samples/config/nacos/base/src/main/java/com/alipay/sofa/config/nacos/DiscoveryController.java
  samples/springboot-samples/config/nacos/base/src/main/java/com/alipay/sofa/config/nacos/NacosApplication.java
  samples/springboot-samples/config/nacos/base/src/main/resources/application.properties
  samples/springboot-samples/config/nacos/base/src/test/java/com/alipay/sofa/config/nacos/NacosApplicationTests.java
  samples/springboot-samples/config/nacos/biz1/conf/ark/rules.txt
  samples/springboot-samples/config/nacos/biz1/pom.xml
  samples/springboot-samples/config/nacos/biz1/src/main/java/com/alipay/sofa/config/nacos/ConfigController.java
  samples/springboot-samples/config/nacos/biz1/src/main/java/com/alipay/sofa/config/nacos/DiscoveryController.java
  samples/springboot-samples/config/nacos/biz1/src/main/java/com/alipay/sofa/config/nacos/NacosApplication.java
  samples/springboot-samples/config/nacos/biz1/src/main/resources/application.properties
  samples/springboot-samples/config/nacos/biz1/src/test/java/com/alipay/sofa/config/nacos/ApolloApplicationTests.java
  samples/springboot-samples/config/nacos/biz2/conf/ark/rules.txt
  samples/springboot-samples/config/nacos/biz2/pom.xml
  samples/springboot-samples/config/nacos/biz2/src/main/java/com/alipay/sofa/config/nacos/ConfigController.java
  samples/springboot-samples/config/nacos/biz2/src/main/java/com/alipay/sofa/config/nacos/NacosApplication.java
  samples/springboot-samples/config/nacos/biz2/src/main/resources/application.properties
  samples/springboot-samples/config/nacos/biz2/src/test/java/com/alipay/sofa/config/nacos/ApolloApplicationTests.java
  samples/springboot-samples/config/nacos/pom.xml
  samples/springboot-samples/pom.xml
Labels: cla:yes, size/XL

#397 remove logback multi context support to sofa-ark
  docs/content/zh-cn/docs/contribution-guidelines/runtime/logback.md
  samples/springboot-samples/logging/logback/base/pom.xml
  samples/springboot-samples/logging/logback/base/src/main/java/com/alipay/sofa/web/base/BaseApplication.java
  samples/springboot-samples/logging/logback/biz1/pom.xml
  samples/springboot-samples/logging/logback/biz2/pom.xml
  samples/springboot-samples/pom.xml
  sofa-serverless-runtime/sofa-serverless-adapter-ext/pom.xml
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/pom.xml
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/main/java/com/alipay/sofa/serverless/logback/SOFAServerlessLogbackLogContextSelector.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/java/com/alipay/sofa/serverless/logback/LogbackDefaultConfigTest.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/java/com/alipay/sofa/serverless/logback/LogbackTest.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/java/com/alipay/sofa/serverless/logback/bootstrap/SOFABootApplication.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/java/com/alipay/sofa/serverless/logback/helper/Log1Print.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/java/com/alipay/sofa/serverless/logback/helper/Log2Print.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/java/com/alipay/sofa/serverless/logback/helper/LogHelper.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/resources/application-logback.properties
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/resources/application.properties
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-logback/src/test/resources/logback-mytest-spring.xml
Labels: cla:yes, size/XL

#404 Update external-articles-and-videos.md
  docs/content/zh-cn/blog/external-articles-and-videos.md
Labels: cla:yes, size/XS

#408 TYPO FIX, "模式"->"模块"
  docs/content/zh-cn/docs/tutorials/module-development/module-debug.md
  docs/content/zh-cn/docs/tutorials/module-development/module-dev-arkctl.md
Labels: bug, First-time contributor, cla:yes, size/XS

#410 update ark to 2.2.5
  docs/content/zh-cn/docs/tutorials/base-create/springboot-and-sofaboot.md
  docs/content/zh-cn/docs/tutorials/module-development/module-slimming.md
  docs/public/docs/_print/index.html
  docs/public/docs/tutorials/_print/index.html
  docs/public/docs/tutorials/base-create/_print/index.html
  docs/public/docs/tutorials/base-create/springboot-and-sofaboot/index.html
  docs/public/docs/tutorials/module-development/_print/index.html
  docs/public/docs/tutorials/module-development/module-slimming/index.html
  samples/dubbo-samples/rpc/dubbo26/pom.xml
  samples/dubbo-samples/rpc/dubbo27/pom.xml
  samples/dubbo-samples/rpc/dubbo3/pom.xml
  samples/sofaboot-samples/dynamic-stock/README.md
  samples/sofaboot-samples/pom.xml
  samples/springboot-samples/pom.xml
  samples/springboot-samples/web/tomcat/biz1/src/main/java/com/alipay/sofa/web/biz1/Biz1Application.java
  samples/springboot-samples/web/webflux/biz/pom.xml
  samples/springboot3-samples/db/mybatis/README.md
  samples/springboot3-samples/logging/README.md
  samples/springboot3-samples/msg/kafka/README.md
  samples/springboot3-samples/web/tomcat/README.md
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/M

#411 update to 0.5.5
  samples/sofaboot-samples/pom.xml
  samples/springboot-samples/pom.xml
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/XS

#421 update ark version for samples
  docs/content/zh-cn/docs/tutorials/module-development/module-dev-arkctl.md
  samples/springboot-samples/pom.xml
  samples/springboot-samples/web/webflux/biz/pom.xml
Labels: cla:yes, size/XS

#426 fix logback sample
  samples/springboot-samples/logging/logback/biz1/src/main/java/com/alipay/sofa/web/biz1/rest/SampleController.java
Labels: bug, cla:yes, size/XS

#423 format lib version
  docs/content/zh-cn/docs/faq/faq.md
  docs/content/zh-cn/docs/faq/imgs/guice_version_incompatibility.png
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/api/ApiClient.java
  sofa-serverless-runtime/pom.xml
  sofa-serverless-runtime/sofa-serverless-common/pom.xml
Labels: cla:yes, size/M

#427 arklet排障性增强
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/api/model/Response.java
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/api/tunnel/http/netty/NettyHttpServer.java
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/util/ExceptionUtils.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/util/ExceptionUtilsTest.java
Labels: cla:yes, size/L

#429 add app starter for biz communication
  docs/content/zh-cn/docs/tutorials/module-development/module-and-base-communication.md
Labels: cla:yes, size/S

#430 Optimize logback sample
  samples/springboot-samples/logging/logback/README.md
  samples/springboot-samples/logging/logback/base/pom.xml
  samples/springboot-samples/logging/logback/base/src/main/resources/application.properties
  samples/springboot-samples/logging/logback/base/src/main/resources/logback-spring.xml
  samples/springboot-samples/logging/logback/biz1/src/main/resources/application.properties
  samples/springboot-samples/logging/logback/biz1/src/main/resources/logback-spring.xml
  samples/springboot-samples/logging/logback/biz2/pom.xml
  samples/springboot-samples/logging/logback/biz2/src/main/java/com/alipay/sofa/springcloud/gateway/biz2/rest/SampleController.java
  samples/springboot-samples/logging/logback/biz2/src/main/java/com/alipay/sofa/web/biz2/Biz2Application.java
  samples/springboot-samples/logging/logback/biz2/src/main/resources/application.properties
  samples/springboot-samples/logging/logback/biz2/src/main/resources/logback-spring.xml
  samples/springboot-samples/logging/logback/biz2/src/test/java/com/alipay/sofa/web/biz2/Biz2ApplicationTests.java
  samples/springboot-samples/logging/logback/img.png
  samples/springboot-samples/logging/logback/img_1.png
  samples/springboot-samples/pom.xml
Labels: cla:yes, size/L
