Repository sofastack/sofa-serverless, pull requests merged in 2023-11, with the labels that each got.

#234 fix docs deploy /home redirect problem
  docs/hugo.toml
  docs/netlify.toml
Labels: bug, cla:yes, size/XS

#231 Liushuo 0.6 fix
  module-controller/api/v1alpha1/module_types.go
  module-controller/api/v1alpha1/moduledeployment_types.go
  module-controller/api/v1alpha1/modulereplicaset_types.go
  module-controller/config/crd/bases/serverless.alipay.com_moduledeployments.yaml
  module-controller/config/crd/bases/serverless.alipay.com_modulereplicasets.yaml
  module-controller/config/crd/bases/serverless.alipay.com_modules.yaml
  module-controller/internal/controller/module_controller.go
  module-controller/internal/controller/module_controller_suit_test.go
  module-controller/internal/controller/moduledeployment_controller.go
  module-controller/internal/controller/moduledeployment_controller_operation_strategy_suit_test.go
  module-controller/internal/controller/moduledeployment_controller_scale_suit_test.go
  module-controller/internal/controller/moduledeployment_controller_upgrade_policy_suit_test.go
  module-controller/internal/controller/modulereplicaset_controller.go
  module-controller/internal/controller/modulereplicaset_controller_suit_test.go
  module-controller/internal/controller/pod_controller.go
  module-controller/internal/controller/pod_controller_suit_test.go
  module-controller/internal/utils/controller_utils.go
  module-controller/internal/utils/controller_utils_test.go
  module-controller/internal/utils/test_utils.go
  module-controller/internal/utils/test_utils_test.go
Labels: bug, cla:yes, size/XL

#233 添加workflow等待模块available
  .github/workflows/module_controller_ci_build_deploy_to_aliyun.yml
  module-controller/config/samples/ci/module-deployment_v1alpha1_moduledeployment_provider_scaledown.yaml
Labels: cla:yes, size/L

#238 add module service doc
  docs/content/zh-cn/docs/tutorials/module-operation/module-service.md
Labels: cla:yes, size/M

#239 添加模块信息、状态、pod上安装的模块查看文档
  docs/content/zh-cn/docs/tutorials/module-operation/module-information-viewing.md
Labels: cla:yes, size/S

#250 test: 补充单元测试
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/api/tunnel/http/netty/NettyHttpServer.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/netty/NettyServerTest.java
Labels: cla:yes, size/M

#255 skip tests
  sofa-serverless-runtime/.codecov.yml
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/M

#256 ServerlessApplicationListener adjust Ordered
  sofa-serverless-runtime/sofa-serverless-common/src/main/java/com/alipay/sofa/serverless/common/spring/ServerlessApplicationListener.java
Labels: cla:yes, size/S

#261 add rocketmq samples
  samples/README.md
  samples/springboot-samples/msg/rocketmq/README.md
  samples/springboot-samples/msg/rocketmq/base/bootstrap/pom.xml
  samples/springboot-samples/msg/rocketmq/base/bootstrap/src/main/java/com/alipay/sofa/base/BaseApplication.java
  samples/springboot-samples/msg/rocketmq/base/bootstrap/src/main/java/com/alipay/sofa/base/service/SampleConsumer.java
  samples/springboot-samples/msg/rocketmq/base/bootstrap/src/main/java/com/alipay/sofa/base/service/SampleProducer.java
  samples/springboot-samples/msg/rocketmq/base/bootstrap/src/main/resources/application.properties
  samples/springboot-samples/msg/rocketmq/base/bootstrap/src/main/resources/log4j2-spring.xml
  samples/springboot-samples/msg/rocketmq/base/bootstrap/src/test/java/com/alipay/sofa/base/BaseApplicationTests.java
  samples/springboot-samples/msg/rocketmq/base/facade/pom.xml
  samples/springboot-samples/msg/rocketmq/base/facade/src/main/java/com/alipay/sofa/base/model/Greeting.java
  samples/springboot-samples/msg/rocketmq/base/pom.xml
  samples/springboot-samples/msg/rocketmq/biz1/pom.xml
  samples/springboot-samples/msg/rocketmq/biz1/src/main/java/com/alipay/sofa/biz1/Biz1Application.java
  samples/springboot-samples/msg/rocketmq/biz1/src/main/java/com/alipay/sofa/biz1/service/SampleConsumer.java
  samples/springboot-samples/msg/rocketmq/biz1/src/main/java/com/alipay/sofa/biz1/service/SampleProducer.java
  samples/springboot-samples/msg/rocketmq/biz1/src/main/resources/application.properties
  samples/springboot-samples/msg/rocketmq/biz1/src/main/resources/log4j2-spring.xml
  samples/springboot-samples/msg/rocketmq/biz1/src/test/java/com/alipay/sofa/base/BaseApplicationTests.java
  samples/springboot-samples/msg/rocketmq/config/broker.conf
  samples/springboot-samples/msg/rocketmq/config/start.sh
  samples/springboot-samples/pom.xml
Labels: cla:yes, size/XL

#259 add grpc samples
  samples/dubbo-samples/rpc/dubbo3/common-model/pom.xml
  samples/dubbo-samples/rpc/dubbo3/common-model/src/main/proto/greeter.proto
  samples/dubbo-samples/rpc/dubbo3/dubbo3base/pom.xml
  samples/dubbo-samples/rpc/dubbo3/grpcbiz/pom.xml
  samples/dubbo-samples/rpc/dubbo3/grpcbiz/src/main/java/com/alipay/sofa/rpc/dubbo3/grpcbiz/rest/RPCController.java
  samples/dubbo-samples/rpc/dubbo3/grpcbiz/src/main/java/com/alipay/sofa/rpc/dubbo3/grpcbiz/service/GrpcBizGreeter.java
  samples/dubbo-samples/rpc/dubbo3/pom.xml
Labels: cla:yes, size/L

#269 add properties for multi jdk
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/S

#266 Compatible springboot3
  .github/workflows/serverless_runtime_snapshot.yml
  samples/springboot3-samples/db/mybatis/README.md
  samples/springboot3-samples/db/mybatis/base/pom.xml
  samples/springboot3-samples/logging/README.md
  samples/springboot3-samples/logging/log4j2/base/pom.xml
  samples/springboot3-samples/msg/kafka/README.md
  samples/springboot3-samples/msg/kafka/base/pom.xml
  samples/springboot3-samples/pom.xml
  samples/springboot3-samples/web/tomcat/README.md
  samples/springboot3-samples/web/tomcat/base/pom.xml
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/M

#210 fix(support springboot1): override method to avoid no default method
  sofa-serverless-runtime/sofa-serverless-common/src/main/java/com/alipay/sofa/serverless/common/service/ArkAutowiredBeanPostProcessor.java
Labels: bug, First-time contributor, cla:yes, size/XS

#277 修改基座Deployment image字段，修复amd64平台无法启动镜像的问题
  module-controller/config/samples/dynamic-stock-deployment.yaml
Labels: cla:yes, size/XS

#285 add release for jdk 17 and jdk8
  .github/workflows/arklet_release.yml
  .github/workflows/arklet_unit_test.yml
  .github/workflows/serverless_runtime_release.yml
  .github/workflows/serverless_runtime_snapshot.yml
  docs/content/zh-cn/docs/video-training/_index.md
  samples/springboot-samples/web/tomcat/config/biz2-deployment.yaml
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/L

#290 update staging plugin version
  docs/content/zh-cn/docs/tutorials/base-create/_index.md
  docs/content/zh-cn/docs/tutorials/base-create/springboot-and-sofaboot.md
  docs/content/zh-cn/docs/tutorials/build_and_deploy.md
  docs/content/zh-cn/docs/tutorials/module-create/_index.md
  docs/content/zh-cn/docs/tutorials/module-create/init_by_archtype.md
  docs/content/zh-cn/docs/tutorials/module-create/springboot-and-sofaboot.md
  docs/content/zh-cn/docs/tutorials/module-development/_index.md
  docs/content/zh-cn/docs/tutorials/module-operation/_index.md
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/S

#279 feat(ark-serverless): support dubbo 2.6
  sofa-serverless-runtime/sofa-serverless-adapter-ext/pom.xml
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-dubbo2.6/pom.xml
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-dubbo2.6/src/main/java/com/alibaba/dubbo/common/ClassLoaderUtil.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-dubbo2.6/src/main/java/com/alibaba/dubbo/common/extension/ExtensionLoader.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-dubbo2.6/src/main/java/com/alibaba/dubbo/common/serialize/java/ClassLoaderJavaObjectInput.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-dubbo2.6/src/main/java/com/alibaba/dubbo/common/serialize/java/ClassLoaderObjectInputStream.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-dubbo2.6/src/main/java/com/alibaba/dubbo/common/serialize/java/JavaSerialization.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-dubbo2.6/src/main/java/com/alibaba/dubbo/config/spring/extension/SpringExtensionFactory.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-dubbo2.6/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DecodeableRpcInvocation.java
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-dubbo2.6/src/main/java/com/alibaba/dubbo/rpc/protocol/dubbo/DecodeableRpcResult.java
Labels: size/XXL, cla:yes

#286 support new arklet for module controller
  module-controller/config/samples/module-deployment-controller.yaml
  module-controller/internal/arklet/arklet_client.go
Labels: cla:yes, size/XS

#287 Feat/ark deploy
  .github/workflows/arkctl_unit_test.yml
  arkctl/common/cmdutil/cmd_util.go
  arkctl/common/cmdutil/cmd_util_test.go
  arkctl/common/cmdutil/pterm_util.go
  arkctl/common/contextutil/context.go
  arkctl/common/contextutil/context_util.go
  arkctl/common/fileutil/file_util.go
  arkctl/common/runtime/runtime_util.go
  arkctl/common/style/style.go
  arkctl/go.mod
  arkctl/go.sum
  arkctl/main.go
  arkctl/v1/cmd/deploy/deploy.go
  arkctl/v1/cmd/gen/gen.go
  arkctl/v1/cmd/init.go
  arkctl/v1/cmd/root/root.go
  arkctl/v1/cmd/show/show.go
  arkctl/v1/cmd/status/status.go
  arkctl/v1/cmd/version/version.go
  arkctl/v1/constant/constant.go
  arkctl/v1/service/ark/biz_util.go
  arkctl/v1/service/ark/biz_util_test.go
  arkctl/v1/service/ark/service.go
  arkctl/v1/service/ark/service_test.go
  arkctl/v1/service/ark/types.go
  docs/content/zh-cn/docs/tutorials/module-development/module-dev-arkctl.md
Labels: First-time contributor, size/XXL, cla:yes

#295 <ci> add arkctl release action
  .github/workflows/arkctl_release.yml
Labels: cla:yes, size/M

#298 <feat> complete ark auto relase action
  .github/workflows/arkctl_release.yml
Labels: cla:yes, size/M

#208 添加 event新类型，添加 计算 基座 Pod上 最大/最小/平均 已被调度模块实例个数 修复ModuleDeployment单测
  module-controller/internal/constants/label/well_known_labels.go
  module-controller/internal/controller/moduledeployment_controller.go
  module-controller/internal/controller/moduledeployment_controller_operation_strategy_suit_test.go
  module-controller/internal/controller/modulereplicaset_controller.go
  module-controller/internal/event/event.go
  module-controller/internal/event/event_test.go
  module-controller/internal/event/modulereplicaset_replicas_changed_event.go
  module-controller/internal/handler/modulereplicaset_replicas_changed_handler.go
  module-controller/internal/handler/modulereplicaset_replicas_changed_handler_test.go
  module-controller/internal/utils/test_utils.go
  module-controller/internal/utils/test_utils_test.go
Labels: cla:yes, size/L

#291 Adjust version
  .github/workflows/serverless_runtime_release.yml
  .github/workflows/serverless_runtime_snapshot.yml
  samples/springboot3-samples/db/mybatis/README.md
  samples/springboot3-samples/db/mybatis/base/pom.xml
  samples/springboot3-samples/logging/README.md
  samples/springboot3-samples/logging/log4j2/base/pom.xml
  samples/springboot3-samples/msg/kafka/README.md
  samples/springboot3-samples/msg/kafka/base/pom.xml
  samples/springboot3-samples/web/tomcat/README.md
  samples/springboot3-samples/web/tomcat/base/pom.xml
  sofa-serverless-runtime/pom.xml
  sofa-serverless-runtime/sofa-serverless-base-starter/pom.xml
  sofa-serverless-runtime/sofa-serverless-common/src/main/java/com/alipay/sofa/serverless/common/util/LoaderUtil.java
  sofa-serverless-runtime/sofa-serverless-common/src/main/java/com/alipay/sofa/serverless/common/util/ReflectionUtils.java
  sofa-serverless-runtime/sofa-serverless-common/src/test/java/com/alipay/sofa/serverless/common/ReflectionUtilsTest.java
  sofa-serverless-runtime/sofa-serverless-common/src/test/java/com/alipay/sofa/serverless/common/SpringServiceFinderTest.java
Labels: cla:yes, size/L

#304 升级fastjson版本1.2.69 到 1.2.83修复fastjson已知漏洞
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/XS

#306 ref sofa ark verson
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/M

#311 add just springbooot3 samples
  .github/workflows/arklet_unit_test.yml
  .github/workflows/serverless_runtime_release.yml
  samples/springboot3-samples/db/mybatis/README.md
  samples/springboot3-samples/db/mybatis/base/pom.xml
  samples/springboot3-samples/logging/README.md
  samples/springboot3-samples/logging/log4j2/base/pom.xml
  samples/springboot3-samples/msg/kafka/README.md
  samples/springboot3-samples/msg/kafka/base/pom.xml
  samples/springboot3-samples/msg/kafka/base/src/main/java/com/alipay/sofa/base/rest/SampleController.java
  samples/springboot3-samples/msg/kafka/base/src/main/resources/application.properties
  samples/springboot3-samples/pom.xml
  samples/springboot3-samples/web/tomcat/README.md
  samples/springboot3-samples/web/tomcat/base/pom.xml
  sofa-serverless-runtime/arklet-springboot-starter/pom.xml
  sofa-serverless-runtime/pom.xml
  sofa-serverless-runtime/sofa-serverless-adapter-ext/sofa-serverless-adapter-log4j2/src/main/java/com/alipay/sofa/serverless/log4j2/SOFAServerlessLog4j2LoggingSystem.java
Labels: cla:yes, size/L

#312 update version to 0.5.3
  docs/content/zh-cn/docs/tutorials/base-create/springboot-and-sofaboot.md
  docs/content/zh-cn/docs/tutorials/trial_step_by_step.md
  samples/dubbo-samples/rpc/dubbo26/pom.xml
  samples/dubbo-samples/rpc/dubbo3/pom.xml
  samples/springboot-samples/cache/ehcache/biz1/conf/ark/rules.txt
  samples/springboot-samples/cache/ehcache/biz2/conf/ark/rules.txt
  samples/springboot-samples/pom.xml
  samples/springboot-samples/slimming/log4j2/biz1/conf/ark/rules.txt
  samples/springboot-samples/web/tomcat/biz1/conf/ark/rules.txt
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/S

#319 update build and deploy docs
  docs/content/zh-cn/docs/tutorials/build_and_deploy.md
  docs/content/zh-cn/docs/tutorials/trial_step_by_step.md
Labels: cla:yes, size/XS

#321 addjust release version for jdk 17
  samples/dubbo-samples/rpc/dubbo26/pom.xml
  samples/dubbo-samples/rpc/dubbo3/pom.xml
  samples/sofaboot-samples/pom.xml
  samples/springboot-samples/pom.xml
  samples/springboot3-samples/db/mybatis/README.md
  samples/springboot3-samples/db/mybatis/base/pom.xml
  samples/springboot3-samples/logging/README.md
  samples/springboot3-samples/logging/log4j2/base/pom.xml
  samples/springboot3-samples/msg/kafka/README.md
  samples/springboot3-samples/msg/kafka/base/pom.xml
  samples/springboot3-samples/pom.xml
  samples/springboot3-samples/web/tomcat/README.md
  samples/springboot3-samples/web/tomcat/base/pom.xml
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/S

#316 sample base dockerfile add telnet
  docs/content/zh-cn/docs/tutorials/module-operation/module-online-and-offline.md
  docs/content/zh-cn/docs/tutorials/module-operation/module-scale-and-replace.md
  docs/public/docs/_print/index.html
  docs/public/docs/tutorials/_print/index.html
  docs/public/docs/tutorials/module-operation/_print/index.html
  docs/public/docs/tutorials/module-operation/module-online-and-offline/index.html
  docs/public/docs/tutorials/module-operation/module-scale-and-replace/index.html
  samples/sofaboot-samples/dynamic-stock/base/Dockerfile
Labels: cla:yes, size/M

#318 修改类名ArkHealthzEndpoint为ArkHealthEndpoint
  sofa-serverless-runtime/arklet-springboot-starter/src/main/java/com/alipay/sofa/serverless/arklet/springboot/starter/health/HealthAutoConfiguration.java
  sofa-serverless-runtime/arklet-springboot-starter/src/main/java/com/alipay/sofa/serverless/arklet/springboot/starter/health/endpoint/ArkHealthEndpoint.java
  sofa-serverless-runtime/arklet-springboot-starter/src/test/java/com/alipay/sofa/serverless/arklet/springboot/starter/health/endpoint/ArkHealthEndpointTest.java
Labels: cla:yes, size/M

#323 add ci test before sofa-runtime release
  .github/workflows/arklet_cd_test.yml
  .github/workflows/serverless_runtime_release.yml
  .github/workflows/serverless_runtime_snapshot.yml
  samples/ccbin/start.sh
Labels: cla:yes, size/L

#317 修改基座image和模块url
  .github/workflows/module_controller_ci_build_deploy_to_aliyun.yml
  docs/content/zh-cn/docs/tutorials/module-operation/module-deployment-and-rollback.md
  docs/content/zh-cn/docs/tutorials/module-operation/module-online-and-offline.md
  docs/content/zh-cn/docs/tutorials/module-operation/module-scale-and-replace.md
  docs/content/zh-cn/docs/tutorials/module-operation/module-service.md
  docs/public/docs/_print/index.html
  docs/public/docs/tutorials/_print/index.html
  docs/public/docs/tutorials/module-operation/_print/index.html
  docs/public/docs/tutorials/module-operation/module-deployment-and-rollback/index.html
  docs/public/docs/tutorials/module-operation/module-online-and-offline/index.html
  docs/public/docs/tutorials/module-operation/module-scale-and-replace/index.html
  docs/public/docs/tutorials/module-operation/module-service/index.html
  module-controller/config/samples/ci/dynamic-stock-deployment.yaml
  module-controller/config/samples/ci/module-deployment_v1alpha1_moduledeployment_provider_scaledown.yaml
  module-controller/config/samples/dynamic-stock-deployment.yaml
  module-controller/config/samples/module-deployment_v1alpha1_moduledeployment_provider.yaml
  samples/sofaboot-samples/dynamic-stock/config/biz1-deployment.yaml
Labels: cla:yes, size/L

#324 Feat/feat combine deploy from local file system in arklet
  docs/content/zh-cn/docs/tutorials/module-development/static-merge-deployment.md
  samples/springboot-samples/web/tomcat/README.md
  samples/springboot-samples/web/tomcat/static-deploy-samples/run_static_deploy_on_unix_like.sh
  sofa-serverless-runtime/arklet-core/pom.xml
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/common/model/BatchInstallRequest.java
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/common/model/BatchInstallResponse.java
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/ops/BatchInstallHelper.java
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/ops/UnifiedOperationService.java
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/ops/UnifiedOperationServiceImpl.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/component/UnifiedOperationServiceImplTests.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/ops/BatchInstallHelperTest.java
  sofa-serverless-runtime/arklet-springboot-starter/pom.xml
  sofa-serverless-runtime/arklet-springboot-starter/src/main/java/com/alipay/sofa/serverless/arklet/springboot/starter/listener/ArkletApplicationListener.java
  sofa-serverless-runtime/pom.xml
  sofa-serverless-runtime/sofa-serverless-base-plugin/pom.xml
  sofa-serverless-runtime/sofa-serverless-base-plugin/src/main/java/com/alipay/sofa/serverless/plugin/manager/listener/StaticBatchInstallEventListener.java
  sofa-serverless-runtime/sofa-serverless-base-plugin/src/main/resources/META-INF/spring.factories
  sofa-serverless-runtime/sofa-serverless-base-plugin/src/test/java/com/alipay/sofa/serverless/plugin/manager/listener/StaticBatchInstallEventListenerTest.java
Labels: cla:yes, size/XL

#303 分组发布ci test
  .github/workflows/module_controller_ci_build_batch_deploy_to_aliyun.yml
  .github/workflows/module_controller_ci_build_deploy_to_aliyun.yml
  module-controller/config/samples/ci/dynamic-stock-batch-deployment.yaml
  module-controller/config/samples/ci/module-deployment_v1alpha1_moduledeployment_batch_provider.yaml
  module-controller/config/samples/ci/module-deployment_v1alpha1_moduledeployment_batch_provider_scaledown.yaml
Labels: cla:yes, size/XL

#334 add activation
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/S

#336 update step by step md
  docs/content/zh-cn/docs/tutorials/trial_step_by_step.md
Labels: cla:yes, size/L

#338 <fix> incompatiable with default release script
  samples/springboot-samples/web/tomcat/README.md
  samples/springboot-samples/web/tomcat/static-deploy-demo/run_static_deploy_on_unix_like.sh
Labels: bug, cla:yes, size/S

#339 build_and_test version check fix
  .github/workflows/serverless_runtime_release.yml
  .github/workflows/serverless_runtime_snapshot.yml
Labels: bug, cla:yes, size/XS

#341 add build plugin comment
  docs/content/zh-cn/docs/tutorials/module-create/springboot-and-sofaboot.md
  samples/springboot-samples/slimming/README.md
  samples/springboot3-samples/db/mybatis/README.md
  samples/springboot3-samples/db/mybatis/base/pom.xml
  samples/springboot3-samples/logging/README.md
  samples/springboot3-samples/logging/log4j2/base/pom.xml
  samples/springboot3-samples/msg/kafka/README.md
  samples/springboot3-samples/msg/kafka/base/pom.xml
  samples/springboot3-samples/pom.xml
  samples/springboot3-samples/web/tomcat/README.md
  samples/springboot3-samples/web/tomcat/base/pom.xml
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/XS

#197 delete modules in batches
  .github/workflows/module_controller_ci_build_deploy_to_aliyun.yml
  module-controller/api/v1alpha1/moduledeployment_types.go
  module-controller/api/v1alpha1/zz_generated.deepcopy.go
  module-controller/config/crd/bases/serverless.alipay.com_moduledeployments.yaml
  module-controller/config/crd/bases/serverless.alipay.com_modulereplicasets.yaml
  module-controller/internal/controller/moduledeployment_controller.go
  module-controller/internal/controller/moduledeployment_controller_operation_strategy_suit_test.go
  module-controller/internal/controller/modulereplicaset_controller.go
Labels: cla:yes, size/L

#345 修改基座samples下base-deployment.yaml image字段为最新基座镜像
  samples/sofaboot-samples/dynamic-stock/config/base-deployment.yaml
Labels: cla:yes, size/XS

#344 update apollo samples
  samples/springboot-samples/config/apollo/README.md
  samples/springboot-samples/config/apollo/base/pom.xml
  samples/springboot-samples/config/apollo/base/src/main/java/com/ctrip/framework/apollo/spring/boot/ApolloApplicationContextInitializer.java
  samples/springboot-samples/config/apollo/base/src/main/resources/META-INF/app.properties
  samples/springboot-samples/config/apollo/base/src/main/resources/application.properties
  samples/springboot-samples/config/apollo/biz1/pom.xml
  samples/springboot-samples/config/apollo/biz2/pom.xml
  samples/springboot-samples/pom.xml
Labels: cla:yes, size/L

#326 samples for webflux in single host
  samples/springboot-samples/db/mybatis/README.md
  samples/springboot-samples/pom.xml
  samples/springboot-samples/web/webflux/README.md
  samples/springboot-samples/web/webflux/base/pom.xml
  samples/springboot-samples/web/webflux/base/src/main/java/com/example/yuan/demowebflux/CityHandler.java
  samples/springboot-samples/web/webflux/base/src/main/java/com/example/yuan/demowebflux/CountryHandler.java
  samples/springboot-samples/web/webflux/base/src/main/java/com/example/yuan/demowebflux/DemowebfluxApplication.java
  samples/springboot-samples/web/webflux/base/src/main/java/com/example/yuan/demowebflux/RouterConfig.java
  samples/springboot-samples/web/webflux/base/src/main/java/com/example/yuan/demowebflux/VillageController.java
  samples/springboot-samples/web/webflux/base/src/main/resources/application-sim.properties
  samples/springboot-samples/web/webflux/base/src/main/resources/application.properties
  samples/springboot-samples/web/webflux/base/src/test/java/com/example/yuan/demowebflux/DemowebfluxApplicationTests.java
  samples/springboot-samples/web/webflux/biz/pom.xml
  samples/springboot-samples/web/webflux/biz/src/main/java/com/example/yuan/bizwebflux/BizHandler.java
  samples/springboot-samples/web/webflux/biz/src/main/java/com/example/yuan/bizwebflux/BizwebfluxApplication.java
  samples/springboot-samples/web/webflux/biz/src/main/java/com/example/yuan/bizwebflux/RouterConfig.java
  samples/springboot-samples/web/webflux/biz/src/main/resources/application.properties
  samples/springboot-samples/web/webflux/biz/src/test/java/com/example/yuan/bizwebflux/BizwebfluxApplicationTests.java
Labels: cla:yes, size/XL

#357 fix health check:apollo base use 8081 port
  .github/workflows/ccbin/healthcheck.sh
  .github/workflows/ccbin/start.sh
Labels: bug, cla:yes, size/S
