Repository sofastack/sofa-serverless, pull requests merged in 2023-10, with the labels that each got.

#138 record meta space
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/builtin/handler/InstallBizHandler.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/handler/BaseHandlerTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/handler/InstallBizHandlerTests.java
Labels: cla:yes, size/M

#139 module controller 0.5 bugfix，修复运维策略和先扩后缩的兼容性问题
  module-controller/api/v1alpha1/moduledeployment_types.go
  module-controller/api/v1alpha1/modulereplicaset_types.go
  module-controller/config/crd/bases/serverless.alipay.com_moduledeployments.yaml
  module-controller/config/crd/bases/serverless.alipay.com_modulereplicasets.yaml
  module-controller/internal/constants/finalizer/well_known_finalizers.go
  module-controller/internal/constants/label/well_known_labels.go
  module-controller/internal/controller/module_controller.go
  module-controller/internal/controller/module_controller_suit_test.go
  module-controller/internal/controller/moduledeployment_controller.go
  module-controller/internal/controller/moduledeployment_controller_suit_test.go
  module-controller/internal/controller/modulereplicaset_controller.go
  module-controller/internal/controller/pod_controller.go
  module-controller/internal/controller/pod_controller_suit_test.go
Labels: cla:yes, size/L

#155 add samples for kafka
  samples/msg/kafka/README.md
  samples/msg/kafka/base/pom.xml
  samples/msg/kafka/base/src/main/java/com/alipay/sofa/base/BaseApplication.java
  samples/msg/kafka/base/src/main/java/com/alipay/sofa/base/facade/SampleService.java
  samples/msg/kafka/base/src/main/java/com/alipay/sofa/base/impl/SampleServiceImpl.java
  samples/msg/kafka/base/src/main/java/com/alipay/sofa/base/rest/SampleController.java
  samples/msg/kafka/base/src/main/resources/META-INF/spring/service.xml
  samples/msg/kafka/base/src/main/resources/application.properties
  samples/msg/kafka/base/src/main/resources/log4j2-spring.xml
  samples/msg/kafka/base/src/test/java/com/alipay/sofa/base/BaseApplicationTests.java
  samples/msg/kafka/biz1/pom.xml
  samples/msg/kafka/biz1/src/main/java/com/alipay/sofa/biz1/Biz1Application.java
  samples/msg/kafka/biz1/src/main/java/com/alipay/sofa/biz1/rest/SampleController.java
  samples/msg/kafka/biz1/src/main/resources/application.properties
  samples/msg/kafka/biz1/src/main/resources/log4j2-spring.xml
  samples/msg/kafka/biz1/src/test/java/com/alipay/sofa/biz1/Biz1ApplicationTests.java
  samples/msg/kafka/biz2/pom.xml
  samples/msg/kafka/biz2/src/main/java/com/alipay/sofa/biz2/Biz2Application.java
  samples/msg/kafka/biz2/src/main/java/com/alipay/sofa/biz2/rest/SampleController.java
  samples/msg/kafka/biz2/src/main/resources/application.properties
  samples/msg/kafka/biz2/src/main/resources/log4j2-spring.xml
  samples/msg/kafka/biz2/src/test/java/com/alipay/sofa/biz2/Biz2ApplicationTests.java
  samples/msg/kafka/config/Dockerfile
  samples/msg/kafka/config/assets/scripts/start-kafka.sh
  samples/msg/kafka/config/assets/supervisor/kafka.ini
  samples/pom.xml
Labels: size/XXL, cla:yes

#171 del queryAllBiz return base information
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/builtin/handler/QueryAllBizHandler.java
Labels: cla:yes, size/XS

#168 fix ClassCastException
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/builtin/handler/InstallBizHandler.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/handler/InstallBizHandlerTests.java
Labels: bug, cla:yes, size/S

#163 Lylingzhen runtime docs
  docs/content/zh-cn/docs/tutorials/module-create/convert-springboot-to-module
  docs/content/zh-cn/docs/tutorials/module-create/springboot-and-sofaboot.md
  docs/content/zh-cn/docs/tutorials/module-development/coding-specification.md
  docs/content/zh-cn/docs/tutorials/module-development/runtime-compatibility-list.md
  docs/content/zh-cn/user-cases/ant-group.md
Labels: cla:yes, size/L

#143 update module controller 0.5 docs
  docs/content/zh-cn/docs/contribution-guidelines/module-controller/crd-definition.md
  docs/content/zh-cn/docs/tutorials/module-operation/module-deployment-and-rollback.md
  docs/content/zh-cn/docs/tutorials/module-operation/module-scale-and-replace.md
Labels: cla:yes, size/S

#188 enable edit docs
  docs/hugo.toml
Labels: cla:yes, size/XS

#190 Update alibaba-aidc.md
  docs/content/zh-cn/user-cases/alibaba-aidc.md
Labels: cla:yes, size/L

#175 Spring cross-context calls with interface
  docs/content/zh-cn/docs/tutorials/module-development/module-and-base-communication.md
  samples/service/sample-service-base/base-bootstrap/pom.xml
  samples/service/sample-service-base/base-bootstrap/src/main/java/com/alipay/sofa/base/BaseApplication.java
  samples/service/sample-service-base/base-bootstrap/src/main/java/com/alipay/sofa/base/EnvClient.java
  samples/service/sample-service-base/base-bootstrap/src/main/java/com/alipay/sofa/base/impl/AppServiceImpl.java
  samples/service/sample-service-base/base-bootstrap/src/main/java/com/alipay/sofa/base/impl/SampleServiceImpl.java
  samples/service/sample-service-base/base-bootstrap/src/main/java/com/alipay/sofa/base/impl/SampleServiceImplNew.java
  samples/service/sample-service-base/base-bootstrap/src/main/java/com/alipay/sofa/base/rest/SampleController.java
  samples/service/sample-service-base/base-bootstrap/src/main/resources/application.properties
  samples/service/sample-service-base/base-facade/pom.xml
  samples/service/sample-service-base/base-facade/src/main/java/com/alipay/sofa/base/facade/AppService.java
  samples/service/sample-service-base/base-facade/src/main/java/com/alipay/sofa/base/facade/SampleService.java
  samples/service/sample-service-base/pom.xml
  samples/service/sample-service-biz/biz-bootstrap/pom.xml
  samples/service/sample-service-biz/biz-bootstrap/src/main/java/com/alipay/sofa/biz/BizApplication.java
  samples/service/sample-service-biz/biz-bootstrap/src/main/java/com/alipay/sofa/biz/TestClient.java
  samples/service/sample-service-biz/biz-bootstrap/src/main/java/com/alipay/sofa/biz/rest/SampleController.java
  samples/service/sample-service-biz/biz-bootstrap/src/main/java/com/alipay/sofa/biz/service/StudentProvider.java
  samples/service/sample-service-biz/biz-bootstrap/src/main/java/com/alipay/sofa/biz/service/TeacherProvider.java
  samples/service/sample-service-biz/biz-bootstrap/src/main/resources/application.properties
  samples/service/sample-service-biz/biz-facade/pom.xml
  samples/service/sample-service-biz/biz-facade/src/main/java/com/alipay/sofa/biz/facade/Param.java
  samples/service/sample-service-biz/biz-facade/src/main/java/com/alipay/sofa/biz/facade/People.java
  samples/service/sample-service-biz/biz-facade/src/main/java/com/alipay/sofa/biz/facade/Provider.java
  samples/service/sample-service-biz/biz-facade/src/main/java/com/alipay/sofa/biz/facade/Result.java
  samples/service/sample-service-biz/biz-facade/src/main/java/com/alipay/sofa/biz/facade/Student.java
  samples/service/sample-service-biz/biz-facade/src/main/java/com/alipay/sofa/biz/facade/Teacher.java
  samples/service/sample-service-biz/pom.xml
  samples/service/sample-service-biz2/biz2-bootstrap/pom.xml
  samples/service/sample-service-biz2/biz2-bootstrap/src/main/java/com/alipay/sofa/biz2/Biz2Application.java
  samples/service/sample-service-biz2/biz2-bootstrap/src/main/java/com/alipay/sofa/biz2/TestClient.java
  samples/service/sample-service-biz2/biz2-bootstrap/src/main/java/com/alipay/sofa/biz2/rest/SampleController.java
  samples/service/sample-service-biz2/biz2-bootstrap/src/main/java/com/alipay/sofa/biz2/service/DefaultProcessor.java
  samples/service/sample-service-biz2/biz2-bootstrap/src/main/java/com/alipay/sofa/biz2/service/SpecialProcessor.java
  samples/service/sample-service-biz2/biz2-bootstrap/src/main/resources/application.properties
  samples/service/sample-service-biz2/biz2-facade/pom.xml
  samples/service/sample-service-biz2/biz2-facade/src/main/java/com/alipay/sofa/biz2/facade/Data.java
  samples/service/sample-service-biz2/biz2-facade/src/main/java/com/alipay/sofa/biz2/facade/Processor.java
  samples/service/sample-service-biz2/biz2-facade/src/main/java/com/alipay/sofa/biz2/facade/Request.java
  samples/service/sample-service-biz2/biz2-facade/src/main/java/com/alipay/sofa/biz2/facade/Response.java
  samples/service/sample-service-biz2/pom.xml
  samples/springboot-samples/pom.xml
  sofa-serverless-runtime/sofa-serverless-common/src/main/java/com/alipay/sofa/serverless/common/api/SpringServiceFinder.java
  sofa-serverless-runtime/sofa-serverless-common/src/main/java/com/alipay/sofa/serverless/common/exception/ErrorCodes.java
  sofa-serverless-runtime/sofa-serverless-common/src/main/java/com/alipay/sofa/serverless/common/service/ArkAutowiredBeanPostProcessor.java
  sofa-serverless-runtime/sofa-serverless-common/src/main/java/com/alipay/sofa/serverless/common/service/ServiceProxyFactory.java
  sofa-serverless-runtime/sofa-serverless-common/src/main/java/com/alipay/sofa/serverless/common/service/SpringServiceInvoker.java
  sofa-serverless-runtime/sofa-serverless-common/src/test/java/com/alipay/sofa/serverless/common/SpringServiceFinderTest.java
Labels: size/XXL, cla:yes

#185 Enable init component for each arkletRegistry independently in multi springContext
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/ArkletComponentRegistry.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/BaseTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/component/ComponentRegistryTest.java
  sofa-serverless-runtime/arklet-springboot-starter/src/main/java/com/alipay/sofa/serverless/arklet/springboot/starter/ArkletAutoConfiguration.java
  sofa-serverless-runtime/arklet-springboot-starter/src/main/java/com/alipay/sofa/serverless/arklet/springboot/starter/health/HealthAutoConfiguration.java
  sofa-serverless-runtime/arklet-springboot-starter/src/main/java/com/alipay/sofa/serverless/arklet/springboot/starter/listener/ArkletApplicationListener.java
  sofa-serverless-runtime/arklet-springboot-starter/src/test/java/com/alipay/sofa/serverless/arklet/spring/SpringbootRunnerTest.java
Labels: cla:yes, size/M

#179 enable test coverage as actually it is
  .github/workflows/arklet_unit_test.yml
  docs/content/zh-cn/docs/tutorials/module-development/runtime-compatibility-list.md
  samples/springboot-samples/README.md
  samples/springboot-samples/logging/README.md
  samples/springboot-samples/logging/log4j2/base/pom.xml
  samples/springboot-samples/logging/log4j2/biz1/pom.xml
  samples/springboot-samples/logging/log4j2/biz2/pom.xml
  samples/springboot-samples/msg/kafka/README.md
  samples/springboot-samples/msg/kafka/base/pom.xml
  samples/springboot-samples/msg/kafka/biz1/pom.xml
  samples/springboot-samples/msg/kafka/biz2/pom.xml
  samples/springboot-samples/pom.xml
  samples/springboot-samples/web/tomcat/README.md
  samples/springboot-samples/web/tomcat/base/pom.xml
  samples/springboot-samples/web/tomcat/biz1/pom.xml
  samples/springboot-samples/web/tomcat/biz2/pom.xml
  sofa-serverless-runtime/README.md
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/BizOpsCommandCoordinatorTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/CommandTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/handler/HealthHandlerTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/handler/HelpHandlerTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/handler/InstallBizHandlerTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/handler/UninstallBizHandlerTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/health/HealthServiceTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/health/indicator/IndicatorTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/util/AssertUtilsTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/util/ConvertUtilsTest.java
  sofa-serverless-runtime/arklet-springboot-starter/src/test/java/com/alipay/sofa/serverless/arklet/springboot/starter/BaseSpringApplication.java
  sofa-serverless-runtime/arklet-springboot-starter/src/test/java/com/alipay/sofa/serverless/arklet/springboot/starter/SpringbootBaseTest.java
  sofa-serverless-runtime/arklet-springboot-starter/src/test/java/com/alipay/sofa/serverless/arklet/springboot/starter/SpringbootRunnerTest.java
  sofa-serverless-runtime/arklet-springboot-starter/src/test/java/com/alipay/sofa/serverless/arklet/springboot/starter/common/SpringbootUtil.java
  sofa-serverless-runtime/arklet-springboot-starter/src/test/java/com/alipay/sofa/serverless/arklet/springboot/starter/health/endpoint/ArkHealthCodeEndpointTest.java
  sofa-serverless-runtime/arklet-springboot-starter/src/test/java/com/alipay/sofa/serverless/arklet/springboot/starter/health/endpoint/ArkHealthzEndpointTest.java
  sofa-serverless-runtime/arklet-springboot-starter/src/test/java/com/alipay/sofa/serverless/arklet/springboot/starter/health/extension/indicator/MasterBizHealthIndicatorTest.java
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/L

#169 support module service
  module-controller/api/v1alpha1/moduledeployment_types.go
  module-controller/api/v1alpha1/zz_generated.deepcopy.go
  module-controller/cmd/main.go
  module-controller/config/crd/bases/serverless.alipay.com_moduledeployments.yaml
  module-controller/config/crd/bases/serverless.alipay.com_modulereplicasets.yaml
  module-controller/config/rbac/role.yaml
  module-controller/config/samples/module-deployment_v1alpha1_moduledeployment_facade.yaml
  module-controller/config/samples/module-deployment_v1alpha1_moduledeployment_provider.yaml
  module-controller/internal/constants/label/well_known_labels.go
  module-controller/internal/controller/module_controller.go
  module-controller/internal/controller/moduledeployment_controller.go
  module-controller/internal/controller/moduledeployment_controller_suit_test.go
  module-controller/internal/controller/moduledeployment_controller_test.go
  module-controller/internal/controller/modulereplicaset_controller.go
  module-controller/internal/controller/modulereplicaset_controller_suit_test.go
  module-controller/internal/controller/pod_controller.go
  module-controller/internal/controller/suite_test.go
  module-controller/internal/event/event.go
  module-controller/internal/event/event_test.go
  module-controller/internal/event/module_create_event.go
  module-controller/internal/event/module_delete_event.go
  module-controller/internal/event/moduledeployment_create_event.go
  module-controller/internal/event/moduledeployment_delete_event.go
  module-controller/internal/event/modulereplicaset_create_event.go
  module-controller/internal/event/modulereplicaset_delete_event.go
  module-controller/internal/handler/service_create_handler.go
  module-controller/internal/handler/service_create_handler_test.go
  module-controller/internal/handler/service_delete_handler.go
  module-controller/internal/handler/service_delete_handler_test.go
  module-controller/internal/utils/controller_utils.go
  module-controller/internal/utils/controller_utils_test.go
  module-controller/internal/utils/test_utils.go
  module-controller/internal/utils/test_utils_test.go
Labels: cla:yes, size/XL

#201 update samples to 0.5.1
  README.md
  docs/content/zh-cn/docs/tutorials/base-create/springboot-and-sofaboot.md
  samples/springboot-samples/README.md
  samples/springboot-samples/bizruntimecontext_not_found.png
  samples/springboot-samples/db/mybatis/README.md
  samples/springboot-samples/db/mybatis/base/pom.xml
  samples/springboot-samples/db/mybatis/biz1/pom.xml
  samples/springboot-samples/logging/README.md
  samples/springboot-samples/logging/log4j2/biz1/pom.xml
  samples/springboot-samples/logging/log4j2/biz2/pom.xml
  samples/springboot-samples/msg/kafka/README.md
  samples/springboot-samples/msg/kafka/biz1/pom.xml
  samples/springboot-samples/msg/kafka/biz2/pom.xml
  samples/springboot-samples/pom.xml
  samples/springboot-samples/service/README.md
  samples/springboot-samples/service/sample-service-base/base-bootstrap/pom.xml
  samples/springboot-samples/service/sample-service-base/pom.xml
  samples/springboot-samples/service/sample-service-biz/biz-bootstrap/pom.xml
  samples/springboot-samples/service/sample-service-biz/pom.xml
  samples/springboot-samples/service/sample-service-biz2/biz2-bootstrap/pom.xml
  samples/springboot-samples/service/sample-service-biz2/pom.xml
  samples/springboot-samples/web/tomcat/README.md
  samples/springboot-samples/web/tomcat/biz1/pom.xml
  samples/springboot-samples/web/tomcat/biz2/pom.xml
Labels: cla:yes, size/L

#192 add test for serverless runtime activator
  .github/workflows/stale.yml
  sofa-serverless-runtime/sofa-serverless-base-plugin/src/test/java/com/alipay/sofa/serverless/plugin/ServerlessRuntimeActivatorTest.java
Labels: cla:yes, size/M

#202 add go code coverage
  .github/workflows/module_controller_unit_test.yml
  module-controller/Makefile
Labels: cla:yes, size/S

#203 Module slimming
  docs/content/zh-cn/docs/tutorials/module-development/module-slimming.md
  samples/springboot-samples/README.md
  samples/springboot-samples/slimming/README.md
  samples/springboot-samples/slimming/imgs/biz1-springboot-res.png
  samples/springboot-samples/slimming/imgs/biz1-springboot.png
  samples/springboot-samples/slimming/imgs/biz1-target.png
  samples/springboot-samples/slimming/log4j2/base/pom.xml
  samples/springboot-samples/slimming/log4j2/base/src/main/java/com/alipay/sofa/web/base/BaseApplication.java
  samples/springboot-samples/slimming/log4j2/base/src/main/java/com/alipay/sofa/web/base/facade/SampleService.java
  samples/springboot-samples/slimming/log4j2/base/src/main/java/com/alipay/sofa/web/base/impl/SampleServiceImpl.java
  samples/springboot-samples/slimming/log4j2/base/src/main/java/com/alipay/sofa/web/base/rest/SampleController.java
  samples/springboot-samples/slimming/log4j2/base/src/main/resources/META-INF/spring/service.xml
  samples/springboot-samples/slimming/log4j2/base/src/main/resources/application.properties
  samples/springboot-samples/slimming/log4j2/base/src/main/resources/log4j2-spring.xml
  samples/springboot-samples/slimming/log4j2/base/src/test/java/com/alipay/sofa/web/base/BaseApplicationTests.java
  samples/springboot-samples/slimming/log4j2/biz1/conf/ark/rules.txt
  samples/springboot-samples/slimming/log4j2/biz1/pom.xml
  samples/springboot-samples/slimming/log4j2/biz1/src/main/java/com/alipay/sofa/web/biz1/Biz1Application.java
  samples/springboot-samples/slimming/log4j2/biz1/src/main/java/com/alipay/sofa/web/biz1/rest/SampleController.java
  samples/springboot-samples/slimming/log4j2/biz1/src/main/resources/application.properties
  samples/springboot-samples/slimming/log4j2/biz1/src/main/resources/log4j2-spring.xml
  samples/springboot-samples/slimming/log4j2/biz1/src/test/java/com/alipay/sofa/web/biz1/Biz1ApplicationTests.java
Labels: cla:yes, size/XL

#212 补充单元测试
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/builtin/handler/QueryAllBizHandler.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/BaseTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/handler/QueryAllBizHandlerTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/handler/SwitchBizHandlerTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/component/UnifiedOperationServiceImplTests.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/logger/LoggerTest.java
Labels: cla:yes, size/L

#216 补充整体单测覆盖率
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/CommandTest.java
  sofa-serverless-runtime/arklet-core/src/test/java/com/alipay/sofa/serverless/arklet/core/command/ProcessRecordHolderTest.java
  sofa-serverless-runtime/sofa-serverless-base-plugin/src/test/java/com/alipay/sofa/serverless/plugin/BaseRuntimeAutoConfigurationTest.java
  sofa-serverless-runtime/sofa-serverless-base-plugin/src/test/java/com/alipay/sofa/serverless/plugin/manager/handler/BeforeBizStartupEventHandlerTest.java
  sofa-serverless-runtime/sofa-serverless-common/src/test/java/com/alipay/sofa/serverless/common/SpringServiceFinderTest.java
Labels: cla:yes, size/L
