Repository sofastack/sofa-serverless, pull requests merged in 2024-01, with the labels that each got.

#401 symmetric deploy
  .github/workflows/module_controller_ci_build_batch_symmetric_deploy_to_aliyun.yml
  module-controller/config/samples/ci/module-deployment_v1alpha1_moduledeployment_symmetric_batch_deploy_provider.yaml
  module-controller/internal/controller/moduledeployment_controller.go
  module-controller/internal/controller/moduledeployment_controller_operation_strategy_suit_test.go
Labels: cla:yes, size/XL

#435 Fixed the issue where the module obtains the base configuration when …
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/api/tunnel/http/netty/NettyHttpServer.java
  sofa-serverless-runtime/sofa-serverless-base-plugin/src/main/java/com/alipay/sofa/serverless/plugin/spring/MasterBizPropertySource.java
Labels: question, cla:yes, size/S

#438 update ark to 2.2.6
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/XS

#439 update ark and serverless version for samples
  docs/content/zh-cn/docs/faq/faq.md
  docs/content/zh-cn/docs/tutorials/base-create/springboot-and-sofaboot.md
  docs/content/zh-cn/docs/tutorials/module-development/module-and-base-communication.md
  docs/content/zh-cn/docs/tutorials/module-development/module-slimming.md
  docs/content/zh-cn/docs/tutorials/trial_step_by_step.md
  samples/dubbo-samples/rpc/dubbo26/README.md
  samples/dubbo-samples/rpc/dubbo26/pom.xml
  samples/dubbo-samples/rpc/dubbo27/dubbo27base/pom.xml
  samples/dubbo-samples/rpc/dubbo27/pom.xml
  samples/dubbo-samples/rpc/dubbo3/pom.xml
  samples/feature-samples/pom.xml
  samples/sofaboot-samples/dynamic-stock/README.md
  samples/sofaboot-samples/pom.xml
  samples/springboot-samples/cache/ehcache/base/pom.xml
  samples/springboot-samples/cache/redis/sample-redis-base/redis-base-bootstrap/pom.xml
  samples/springboot-samples/config/nacos/base/pom.xml
  samples/springboot-samples/db/mongo/base/bootstrap/pom.xml
  samples/springboot-samples/db/mybatis/base/pom.xml
  samples/springboot-samples/logging/logback/base/pom.xml
  samples/springboot-samples/msg/kafka/base/pom.xml
  samples/springboot-samples/msg/rocketmq/base/bootstrap/pom.xml
  samples/springboot-samples/pom.xml
  samples/springboot-samples/service/sample-service-base/base-bootstrap/pom.xml
  samples/springboot-samples/slimming/log4j2/base/pom.xml
  samples/springboot-samples/springcloud/gateway/base/pom.xml
  samples/springboot-samples/web/tomcat/base/bootstrap/pom.xml
  samples/springboot-samples/web/webflux/base/pom.xml
  samples/springboot3-samples/db/mybatis/README.md
  samples/springboot3-samples/logging/README.md
  samples/springboot3-samples/msg/kafka/README.md
  samples/springboot3-samples/web/tomcat/README.md
Labels: cla:yes, size/L

#440 fix missed lib
  samples/springboot-samples/service/sample-service-base/base-bootstrap/pom.xml
Labels: bug, cla:yes, size/S

#441 update to 0.5.6
  docs/content/zh-cn/docs/faq/faq.md
  docs/content/zh-cn/docs/tutorials/base-create/springboot-and-sofaboot.md
  docs/content/zh-cn/docs/tutorials/module-development/module-and-base-communication.md
  docs/content/zh-cn/docs/tutorials/trial_step_by_step.md
  samples/dubbo-samples/rpc/dubbo26/pom.xml
  samples/dubbo-samples/rpc/dubbo27/pom.xml
  samples/dubbo-samples/rpc/dubbo3/pom.xml
  samples/feature-samples/pom.xml
  samples/sofaboot-samples/pom.xml
  samples/springboot-samples/pom.xml
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/S

#446 add warn for no biz name or version when install biz
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/builtin/handler/InstallBizHandler.java
Labels: question, cla:yes, size/XS

#444 fix bug 442，invoke producted method error
  sofa-serverless-runtime/sofa-serverless-common/src/main/java/com/alipay/sofa/serverless/common/service/SpringServiceInvoker.java
Labels: bug, First-time contributor, cla:yes, size/XS

#447 add tips for import base starter
  samples/springboot-samples/cache/ehcache/README.md
  samples/springboot-samples/cache/ehcache/base/pom.xml
  samples/springboot-samples/cache/redis/README.md
  samples/springboot-samples/cache/redis/sample-redis-base/redis-base-bootstrap/pom.xml
  samples/springboot-samples/config/apollo/base/pom.xml
  samples/springboot-samples/config/nacos/base/pom.xml
  samples/springboot-samples/db/mongo/README.md
  samples/springboot-samples/db/mongo/base/bootstrap/pom.xml
  samples/springboot-samples/db/mybatis/README.md
  samples/springboot-samples/db/mybatis/base/pom.xml
  samples/springboot-samples/logging/log4j2/README.md
  samples/springboot-samples/logging/log4j2/base/pom.xml
  samples/springboot-samples/logging/logback/README.md
  samples/springboot-samples/logging/logback/base/pom.xml
  samples/springboot-samples/msg/kafka/README.md
  samples/springboot-samples/msg/kafka/base/pom.xml
  samples/springboot-samples/msg/rocketmq/README.md
  samples/springboot-samples/msg/rocketmq/base/bootstrap/pom.xml
  samples/springboot-samples/service/README.md
  samples/springboot-samples/service/sample-service-base/base-bootstrap/pom.xml
  samples/springboot-samples/slimming/README.md
  samples/springboot-samples/slimming/log4j2/base/pom.xml
  samples/springboot-samples/springcloud/gateway/README.md
  samples/springboot-samples/springcloud/gateway/base/pom.xml
  samples/springboot-samples/web/tomcat/README.md
  samples/springboot-samples/web/tomcat/base/bootstrap/pom.xml
  samples/springboot-samples/web/webflux/README.md
  samples/springboot-samples/web/webflux/base/pom.xml
Labels: cla:yes, size/L

#448 <doc> add doc
  docs/content/zh-cn/docs/contribution-guidelines/runtime/multi-app-padater.md
Labels: cla:yes, size/M

#449 using base override for dubbo
  docs/hugo.toml
  samples/dubbo-samples/rpc/dubbo26/dubbo26base/pom.xml
  samples/dubbo-samples/rpc/dubbo27/dubbo27base/pom.xml
  samples/dubbo-samples/rpc/dubbo27/dubbo27biz/pom.xml
  samples/dubbo-samples/rpc/dubbo27/dubbo27biz2/pom.xml
  samples/dubbo-samples/rpc/dubbo3/dubbo3base/pom.xml
  samples/dubbo-samples/rpc/dubbo3/grpcbiz/pom.xml
  samples/dubbo-samples/rpc/dubbo3/triplebiz/pom.xml
Labels: cla:yes, size/L

#454 Update _index.md
  docs/content/zh-cn/docs/video-training/_index.md
Labels: First-time contributor, cla:no, size/XS

#457 Update _index.md
  docs/content/zh-cn/docs/video-training/_index.md
Labels: cla:yes, size/XS

#458 fix oscollege intro image location
  docs/content/zh-cn/docs/video-training/_index.md
  docs/public/docs/_print/index.html
  docs/public/docs/contribution-guidelines/runtime/multi-app-padater/index.html
  docs/public/docs/video-training/_print/index.html
  docs/public/docs/video-training/index.html
  docs/public/img/oscollege_intro.png
  docs/public/sitemap.xml
  docs/public/zh-cn/sitemap.xml
  docs/static/img/oscollege_intro.png
Labels: bug, cla:yes, size/M

#463 Fix the error in the base calling biz module in the sample code
  samples/springboot-samples/service/README.md
  samples/springboot-samples/service/sample-service-biz/biz-bootstrap/pom.xml
Labels: bug, cla:no, size/S

#434 使用usebeta分组分组数+1
  module-controller/internal/controller/moduledeployment_controller.go
  module-controller/internal/controller/moduledeployment_controller_operation_strategy_suit_test.go
Labels: cla:yes, size/XS

#465 init without non-type bean
  sofa-serverless-runtime/arklet-springboot-starter/src/main/java/com/alipay/sofa/serverless/arklet/springboot/starter/health/HealthAutoConfiguration.java
Labels: cla:yes, size/S

#469 optimize pom defination
  samples/springboot-samples/pom.xml
  samples/springboot-samples/service/base/base-bootstrap/src/main/java/com/alipay/sofa/base/rest/SampleController.java
  samples/springboot-samples/service/base/pom.xml
  samples/springboot-samples/service/biz1/pom.xml
  samples/springboot-samples/service/biz2/pom.xml
  samples/springboot-samples/service/pom.xml
  samples/springboot3-samples/pom.xml
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/ArkletComponentRegistry.java
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/command/record/ProcessRecord.java
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/health/HealthServiceImpl.java
  sofa-serverless-runtime/arklet-core/src/main/java/com/alipay/sofa/serverless/arklet/core/ops/BatchInstallHelper.java
  sofa-serverless-runtime/arklet-springboot-starter/pom.xml
  sofa-serverless-runtime/pom.xml
  sofa-serverless-runtime/sofa-serverless-base-plugin/src/main/java/com/alipay/sofa/serverless/plugin/manager/listener/StaticBatchInstallEventListener.java
  sofa-serverless-runtime/sofa-serverless-common/src/main/java/com/alipay/sofa/serverless/common/util/SerializeUtils.java
Labels: cla:yes, size/L

#470 Update import-full-springboot-in-module.md
  docs/content/zh-cn/docs/faq/import-full-springboot-in-module.md
Labels: cla:yes, size/XS

#468 fix dubbo error when loading biz module in samples/dubbo-samples/rpc/…
  samples/dubbo-samples/rpc/dubbo26/dubbo26biz/src/main/resources/application.properties
  samples/dubbo-samples/rpc/dubbo26/dubbo26biz2/src/main/resources/application.properties
Labels: bug, question, cla:yes, size/XS

#474 fix cross calling
  samples/springboot-samples/service/biz2/biz2-bootstrap/src/main/java/com/alipay/sofa/biz2/rest/SampleController.java
Labels: bug, cla:yes, size/XS

#475 Update arch-principle.md
  docs/content/zh-cn/docs/introduction/architecture/arch-principle.md
Labels: cla:yes, size/XS

#452 Add biz system properties support 394 feature
  sofa-serverless-runtime/sofa-serverless-common/src/main/java/com/alipay/sofa/serverless/common/util/MultiBizProperties.java
  sofa-serverless-runtime/sofa-serverless-common/src/test/java/com/alipay/sofa/serverless/common/util/MultiBizPropertiesTest.java
Labels: cla:yes, size/XL

#477 update ark version
  docs/content/zh-cn/docs/tutorials/base-create/springboot-and-sofaboot.md
  samples/dubbo-samples/rpc/dubbo26/pom.xml
  samples/dubbo-samples/rpc/dubbo27/pom.xml
  samples/dubbo-samples/rpc/dubbo3/pom.xml
  samples/feature-samples/pom.xml
  samples/sofaboot-samples/pom.xml
  samples/springboot-samples/pom.xml
  sofa-serverless-runtime/pom.xml
Labels: cla:yes, size/S

#406 添加confirm确认显式指定分批数，保证幂等
  .github/workflows/module_controller_ci_build_batch_deploy_to_aliyun.yml
  .github/workflows/module_controller_ci_build_batch_scaleup_then_scaledown_deploy_to_aliyun.yml
  .github/workflows/module_controller_ci_build_batch_symmetric_deploy_to_aliyun.yml
  module-controller/api/v1alpha1/moduledeployment_types.go
  module-controller/config/crd/bases/serverless.alipay.com_moduledeployments.yaml
  module-controller/internal/controller/moduledeployment_controller.go
  module-controller/internal/controller/moduledeployment_controller_operation_strategy_suit_test.go
Labels: cla:yes, size/L
